version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loads_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/loads_db
    ports:
      - "10000:10000"
    depends_on:
      - db

  dashboard:
    build:
      context: ./dash
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/loads_db
    ports:
      - "8501:8501"
    depends_on:
      - db

volumes:
  db_data:
