# render.yaml
services:
  # FastAPI backend for load search and call logging
  - type: web
    name: loads-api
    runtime: docker
    branch: main
    region: oregon
    dockerfilePath: Dockerfile
    plan: free
    buildCommand: |
      # provision schema and seed sample data
      psql "$DATABASE_URL" -f db/schema.sql
      python db/seed.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: loads-db
          property: connectionString
      - key: API_KEY
        value: "${API_KEY}"   

  # Streamlit dashboard for metrics
  - type: web
    name: sales-dashboard
    runtime: docker
    branch: main
    region: oregon
    dockerfilePath: dash/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: loads-db
          property: connectionString

databases:
  - name: loads-db
    plan: free
    postgresMajorVersion: '15'
